# This is the standard conda configuration file. Use this file to list
# the conda packages that you need installed in your environment.
channels:
  - conda-forge
  - pytorch
dependencies:
  #- jupyter_contrib_nbextensions # jupyter-lab doesn't use this any more
  - jupyterhub-singleuser
  # Set default python version to 3.11 - repo2docker sets it to 3.7 instead by default,
  # which can limit us to older package versions
  - python=3.11
  # Everyone wants to use nbgitpuller for everything, so let's do that
  - nbgitpuller=1.1.*
  # Add other packages here:
  - numpy
  - matplotlib
  - scipy
  - pandas
  - tqdm
  - s3fs
  - awscli
  - scikit-learn
  - datalad
  - datalad-container
  - singularity
  - altair
  - seaborn
  - graphviz
  - pygraphviz
  - python-graphviz
  - jax
  - numba
  - cython
  - pytorch==2.3.1
  - torchvision==0.18
  - pytorch::cpuonly
  - dcm2niix
  - openneuro-py
  - ipyvolume
  - nodejs
  - s5cmd
  - imbalanced-learn
  - tensorflow
  - nitime
  - openneuro-py
  - pip
  - pip:
    - pybids
    - nipype
    - neuropythy>=0.12.16
    - dipy
    - nilearn
    - dask[complete]
    - nimare
    - osfclient
    - line_profiler
    - memory_profiler
    - black
    - ipympl
    - pliers
    - duecredit
    - git-credential-helpers
    - cloudpathlib[s3,gs,azure]
    - colorspacious
    - requests
    - platformdirs
    - jupyter-keepalive
    - git+https://github.com/NeuroHackademy2025/rbc-projects-template@main
